project:
  type: website

website:
  title: "VisionLabels"
  navbar:
    logo: "logo.png"
    left:
      # - href: index.qmd
      #   text: Home
      - people.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



