project:
  type: website
  output-dir: docs

website:
  title: "VisionLabels"
  navbar:
    logo: "logo.png"
    left:
      # - href: index.qmd
      #   text: Home
      - people.qmd
      - projects.qmd
      - publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



